"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import {
  Send, LogOut, ChevronDown, ChevronUp, Bot, User,
  Upload, FileText, Trash2, Plus, CircleDot, Settings,
  Download, MessageSquare, History, FolderOpen, PenLine,
  Mic, MicOff, Share2, Search, X, Check, Link,
} from "lucide-react";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { cn } from "@/lib/utils";
import { resolveAvatar } from "@/lib/avatar";
import {
  createSession, loadSessions, loadMessages, saveMessage,
  updateSessionTitle, deleteSession,
  searchChatHistory, shareSession, unshareSession, isSessionShared,
  type ChatSession, type SearchResult,
} from "@/lib/chat-history";

// Use the local Next.js API proxy to securely attach the API key
const RAG_API = "/api/rag";
const DOCS_API = RAG_API + "/documents";
const UPLOAD_API = RAG_API + "/upload";
const DELETE_API = (name: string) => `${RAG_API}/documents/${encodeURIComponent(name)}`;

// ── Types ────────────────────────────────────────────────
interface DocFile { name: string; size_kb: number }
interface Source { document: string; snippet: string; score: number }
interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: Source[];
  confidence?: "high" | "medium" | "low";
  loading?: boolean;
}

// ── PDF Export ───────────────────────────────────────────
async function exportAnswerPDF(
  question: string,
  answer: string,
  sources: Source[],
  confidence: string,
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const maxW = pageW - margin * 2;
  let y = 20;

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" | "italic",
    color: [number, number, number] = [30, 30, 30],
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxW) as string[];
    lines.forEach((line) => {
      if (y > 272) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += size * 0.45;
    });
    y += 2;
  };

  // Header bar
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setFontSize(11); doc.setFont("helvetica", "bold"); doc.setTextColor(255, 255, 255);
  doc.text("RAG Document QA — Export", margin, 9);
  doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(180, 180, 180);
  doc.text(new Date().toLocaleString(), pageW - margin, 9, { align: "right" });
  y = 22;

  // Confidence pill
  const confColor: [number, number, number] =
    confidence === "high" ? [16, 185, 129] :
      confidence === "medium" ? [245, 158, 11] : [239, 68, 68];
  doc.setFillColor(...confColor);
  doc.roundedRect(margin, y - 4, 42, 6, 1.5, 1.5, "F");
  doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.setTextColor(255, 255, 255);
  doc.text(`${confidence?.toUpperCase()} CONFIDENCE`, margin + 3, y);
  y += 8;

  // Question
  addText("Question", 8, "bold", [140, 140, 140]);
  addText(question, 13, "bold");
  y += 2;

  // Divider
  doc.setDrawColor(220, 220, 220); doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y); y += 6;

  // Answer
  addText("Answer", 8, "bold", [140, 140, 140]);
  addText(answer, 11, "normal");

  // Sources
  if (sources.length > 0) {
    y += 4;
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, pageW - margin, y); y += 6;
    addText("Sources", 8, "bold", [140, 140, 140]);
    sources.forEach((s, i) => {
      const pct = Math.round(s.score * 100);
      addText(`${i + 1}. ${s.document}  (${pct}% match)`, 9.5, "bold");
      if (s.snippet) addText(`"${s.snippet}"`, 9, "italic", [100, 100, 100]);
      y += 2;
    });
  }

  // Footer
  doc.setFontSize(7.5); doc.setFont("helvetica", "normal"); doc.setTextColor(180, 180, 180);
  doc.text("Generated by RAG Document QA Bot", margin, 290);

  doc.save("rag-answer.pdf");
}

// ── Small components ─────────────────────────────────────
function ConfidenceBadge({ level }: { level: "high" | "medium" | "low" }) {
  const map = {
    high: { bar: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30", dot: "bg-emerald-400", label: "High confidence" },
    medium: { bar: "bg-amber-500/15 text-amber-400 border-amber-500/30", dot: "bg-amber-400", label: "Medium confidence" },
    low: { bar: "bg-red-500/15 text-red-400 border-red-500/30", dot: "bg-red-400", label: "Low confidence" },
  };
  const c = map[level];
  return (
    <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-medium", c.bar)}>
      <span className={cn("h-1.5 w-1.5 rounded-full", c.dot)} />
      {c.label}
    </span>
  );
}

function SourceCard({ source }: { source: Source }) {
  const [open, setOpen] = React.useState(false);
  const pct = Math.round(source.score * 100);
  const pctColor = pct >= 68 ? "text-emerald-400" : pct >= 52 ? "text-amber-400" : "text-red-400";
  return (
    <div className="rounded-lg border border-white/8 bg-white/2 overflow-hidden">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-2 px-3 py-2 text-left hover:bg-white/4 transition-colors"
      >
        <FileText className="h-3.5 w-3.5 shrink-0 text-white/25" />
        <span className="flex-1 truncate text-xs text-white/60 font-medium">{source.document}</span>
        <span className={cn("shrink-0 text-xs font-semibold", pctColor)}>{pct}%</span>
        {open ? <ChevronUp className="h-3 w-3 shrink-0 text-white/25" /> : <ChevronDown className="h-3 w-3 shrink-0 text-white/25" />}
      </button>
      {open && (
        <div className="border-t border-white/6 px-3 py-2.5">
          <p className="text-xs leading-relaxed text-white/45 italic">&ldquo;{source.snippet}&rdquo;</p>
        </div>
      )}
    </div>
  );
}

function MessageBubble({
  msg,
  onExport,
}: {
  msg: Message;
  onExport?: (msg: Message) => void;
}) {
  const isUser = msg.role === "user";
  return (
    <div className={cn("flex gap-3", isUser ? "flex-row-reverse" : "flex-row")}>
      <div className={cn(
        "mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border text-xs font-semibold",
        isUser ? "border-white/15 bg-white/8 text-white/60" : "border-white/10 bg-[#111] text-white/40",
      )}>
        {isUser ? <User className="h-4 w-4" /> : <Bot className="h-4 w-4" />}
      </div>

      <div className={cn("flex max-w-[75%] flex-col gap-2", isUser && "items-end")}>
        {msg.loading ? (
          <div className="rounded-2xl rounded-tl-sm border border-white/8 bg-[#0f0f0f] px-4 py-3.5 flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-white/40 [animation-delay:0ms]" />
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-white/40 [animation-delay:150ms]" />
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-white/40 [animation-delay:300ms]" />
          </div>
        ) : (
          <div className={cn(
            "rounded-2xl px-4 py-3 text-sm leading-relaxed whitespace-pre-wrap",
            isUser
              ? "rounded-tr-sm bg-white text-black font-medium"
              : "rounded-tl-sm border border-white/8 bg-[#0f0f0f] text-white/85",
          )}>
            {msg.content}
          </div>
        )}

        {!isUser && !msg.loading && msg.confidence && (
          <div className="flex flex-col gap-2 w-full">
            <div className="flex items-center gap-2 flex-wrap">
              <ConfidenceBadge level={msg.confidence} />
              {onExport && (
                <button
                  onClick={() => onExport(msg)}
                  title="Export as PDF"
                  className="inline-flex items-center gap-1 rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-white/30 hover:text-white/60 hover:border-white/25 transition-colors"
                >
                  <Download className="h-3 w-3" />
                  PDF
                </button>
              )}
            </div>
            {msg.sources && msg.sources.length > 0 && (
              <>
                <p className="text-[10px] font-semibold tracking-widest text-white/20 uppercase px-0.5">Sources</p>
                <div className="flex flex-col gap-1.5">
                  {msg.sources.map((s, i) => <SourceCard key={i} source={s} />)}
                </div>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────
export default function ChatPage() {
  const router = useRouter();

  // ── Auth ────────────────────────────────────────────────
  const [user, setUser] = React.useState<any>(null);
  const [authChecked, setAuthChecked] = React.useState(false);

  // ── Messages ────────────────────────────────────────────
  const [messages, setMessages] = React.useState<Message[]>([]);
  const [input, setInput] = React.useState("");
  const [sending, setSending] = React.useState(false);

  // ── Documents ───────────────────────────────────────────
  const [docs, setDocs] = React.useState<DocFile[]>([]);
  const [uploading, setUploading] = React.useState(false);
  const [deleting, setDeleting] = React.useState<string | null>(null);

  // ── Sidebar / history ────────────────────────────────────
  const [sidebarTab, setSidebarTab] = React.useState<"files" | "history">("files");
  const [sessions, setSessions] = React.useState<ChatSession[]>([]);
  const [sessionId, setSessionId] = React.useState<string | null>(null);
  const [loadingHist, setLoadingHist] = React.useState(false);

  // ── Search ────────────────────────────────────────────────
  const [historySearch, setHistorySearch] = React.useState("");
  const [searchResults, setSearchResults] = React.useState<SearchResult[]>([]);
  const [isSearching, setIsSearching] = React.useState(false);

  // ── Share ─────────────────────────────────────────────────
  const [sharedSessions, setSharedSessions] = React.useState<Set<string>>(new Set());
  const [shareCopied, setShareCopied] = React.useState<string | null>(null);

  // ── Voice ─────────────────────────────────────────────────
  const [listening, setListening] = React.useState(false);
  const recognitionRef = React.useRef<any>(null);

  // ── Profile dropdown ─────────────────────────────────────
  const [profileOpen, setProfileOpen] = React.useState(false);

  // ── Refs ────────────────────────────────────────────────
  const bottomRef = React.useRef<HTMLDivElement>(null);
  const inputRef = React.useRef<HTMLTextAreaElement>(null);
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const profileRef = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    function handler(e: MouseEvent) {
      if (profileRef.current && !profileRef.current.contains(e.target as Node))
        setProfileOpen(false);
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  // ── Search debounce ───────────────────────────────────────
  React.useEffect(() => {
    if (!historySearch.trim()) { setSearchResults([]); return; }
    const t = setTimeout(async () => {
      if (!user) return;
      setIsSearching(true);
      const results = await searchChatHistory(user.id, historySearch);
      setSearchResults(results);
      setIsSearching(false);
    }, 300);
    return () => clearTimeout(t);
  }, [historySearch, user]);

  // ── Auth guard + session init ─────────────────────────
  React.useEffect(() => {
    if (!isSupabaseConfigured) { setAuthChecked(true); return; }
    const supabase = createClient();
    if (!supabase) { setAuthChecked(true); return; }
    supabase.auth.getUser().then(async ({ data }) => {
      if (!data.user) {
        router.replace("/");
      } else {
        setUser(data.user);
        setAuthChecked(true);
        const id = await createSession(data.user.id);
        setSessionId(id);
        const s = await loadSessions(data.user.id);
        setSessions(s);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [router]);

  React.useEffect(() => { fetchDocs(); }, []);

  async function fetchDocs() {
    try {
      const res = await fetch(DOCS_API);
      if (!res.ok) return;
      const data = await res.json();
      setDocs(data.documents ?? []);
    } catch { /* backend offline */ }
  }

  React.useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // ── Session helpers ──────────────────────────────────────
  async function handleNewChat() {
    if (!user) return;
    const id = await createSession(user.id);
    setSessionId(id);
    setMessages([]);
    const s = await loadSessions(user.id);
    setSessions(s);
    setSidebarTab("files");
  }

  async function handleLoadSession(sid: string) {
    setLoadingHist(true);
    setSessionId(sid);
    const msgs = await loadMessages(sid);
    const restored: Message[] = msgs.map((m) => ({
      id: m.id,
      role: m.role as "user" | "assistant",
      content: m.content,
      sources: (m.sources as unknown as Source[]) ?? [],
      confidence: (m.confidence as "high" | "medium" | "low") ?? undefined,
    }));
    setMessages(restored);
    setLoadingHist(false);
    setSidebarTab("files");
  }

  async function handleDeleteSession(e: React.MouseEvent, sid: string) {
    e.stopPropagation();
    await deleteSession(sid);
    if (sessionId === sid) await handleNewChat();
    else {
      const s = await loadSessions(user.id);
      setSessions(s);
    }
  }

  async function handleShare(e: React.MouseEvent, sid: string) {
    e.stopPropagation();
    const alreadyShared = sharedSessions.has(sid);
    if (alreadyShared) {
      await unshareSession(sid);
      setSharedSessions((prev) => { const n = new Set(prev); n.delete(sid); return n; });
    } else {
      await shareSession(sid);
      setSharedSessions((prev) => new Set([...prev, sid]));
      const link = `${window.location.origin}/share/${sid}`;
      await navigator.clipboard.writeText(link).catch(() => { });
      setShareCopied(sid);
      setTimeout(() => setShareCopied(null), 2500);
    }
  }

  function toggleVoice() {
    const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SR) { alert("Voice input is not supported in this browser. Try Chrome or Edge."); return; }
    if (listening) {
      recognitionRef.current?.stop();
      setListening(false);
      return;
    }
    const rec = new SR();
    rec.continuous = false;
    rec.interimResults = true;
    rec.lang = "en-US";
    rec.onstart = () => setListening(true);
    rec.onend = () => { setListening(false); inputRef.current?.focus(); };
    rec.onerror = () => setListening(false);
    rec.onresult = (e: any) => {
      const transcript = Array.from(e.results as any[])
        .map((r: any) => r[0].transcript).join("");
      setInput(transcript);
    };
    recognitionRef.current = rec;
    rec.start();
  }

  // ── Auth ────────────────────────────────────────────────
  async function signOut() {
    const supabase = createClient();
    await supabase?.auth.signOut();
    router.replace("/");
  }

  // ── File ops ─────────────────────────────────────────────
  async function handleUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    const form = new FormData();
    form.append("file", file);
    try {
      const res = await fetch(UPLOAD_API, { method: "POST", body: form });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail ?? "Upload failed");
      setDocs(data.documents ?? []);
    } catch (err: any) {
      alert(err.message);
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }

  async function handleDelete(name: string) {
    setDeleting(name);
    try {
      const res = await fetch(DELETE_API(name), { method: "DELETE" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail ?? "Delete failed");
      setDocs(data.documents ?? []);
    } catch (err: any) {
      alert(err.message);
    } finally {
      setDeleting(null);
    }
  }

  // ── PDF export ────────────────────────────────────────────
  function handleExport(msg: Message) {
    const idx = messages.findIndex((m) => m.id === msg.id);
    const q = messages.slice(0, idx).filter((m) => m.role === "user").pop();
    exportAnswerPDF(q?.content ?? "Question", msg.content, msg.sources ?? [], msg.confidence ?? "low");
  }

  // ── Send message ─────────────────────────────────────────
  async function sendMessage() {
    const question = input.trim();
    if (!question || sending) return;

    const userMsg: Message = { id: Date.now().toString(), role: "user", content: question };
    const placeholderId = Date.now().toString() + "-ai";
    const placeholder: Message = { id: placeholderId, role: "assistant", content: "", loading: true };

    setMessages((prev) => [...prev, userMsg, placeholder]);
    setInput("");
    setSending(true);

    // Persist user message
    if (sessionId && user) {
      await saveMessage(sessionId, user.id, "user", question);
      // Name the session after the first question
      const isFirst = !messages.some((m) => m.role === "user");
      if (isFirst) {
        await updateSessionTitle(sessionId, question);
        const s = await loadSessions(user.id);
        setSessions(s);
      }
    }

    // Build history for multi-turn memory (last 8 turns)
    const history = messages
      .filter((m) => !m.loading && m.content)
      .slice(-8)
      .map((m) => ({ role: m.role, content: m.content }));

    try {
      const res = await fetch(RAG_API + "/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question, history }),
      });
      if (!res.ok) throw new Error(`API error ${res.status}`);
      const data = await res.json();

      setMessages((prev) =>
        prev.map((m) =>
          m.id === placeholderId
            ? { ...m, loading: false, content: data.answer, sources: data.sources, confidence: data.confidence }
            : m,
        ),
      );

      // Persist assistant reply
      if (sessionId && user) {
        await saveMessage(sessionId, user.id, "assistant", data.answer, data.sources ?? [], data.confidence ?? null);
      }
    } catch {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === placeholderId
            ? { ...m, loading: false, content: "Could not reach the RAG API. Make sure the backend is running on port 8000." }
            : m,
        ),
      );
    } finally {
      setSending(false);
      inputRef.current?.focus();
    }
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); }
  }

  // ── Loading screen ─────────────────────────────────────
  if (!authChecked) {
    return (
      <div className="flex h-screen items-center justify-center bg-black">
        <span className="h-6 w-6 animate-spin rounded-full border-2 border-white/20 border-t-white" />
      </div>
    );
  }

  const displayName = user?.user_metadata?.full_name || user?.email?.split("@")[0] || "You";
  const avatarSrc = user ? resolveAvatar(user.id, user.user_metadata?.avatar_url) : null;
  const avatarLetter = (displayName as string)[0]?.toUpperCase() ?? "U";

  return (
    <div className="flex h-screen bg-black overflow-hidden">

      {/* ── LEFT SIDEBAR ─────────────────────────────────── */}
      <aside className="flex w-60 shrink-0 flex-col border-r border-white/8 bg-[#080808]">

        {/* Tab bar */}
        <div className="flex shrink-0 border-b border-white/8">
          {(["files", "history"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setSidebarTab(tab)}
              className={cn(
                "flex flex-1 items-center justify-center gap-1.5 py-3 text-[10px] font-semibold uppercase tracking-widest transition-colors",
                sidebarTab === tab
                  ? "text-white/70 border-b-2 border-white/25 -mb-px"
                  : "text-white/20 hover:text-white/40",
              )}
            >
              {tab === "files" ? <FolderOpen className="h-3.5 w-3.5" /> : <History className="h-3.5 w-3.5" />}
              {tab}
            </button>
          ))}
        </div>

        {/* ─── FILES ─────────────────────────────────────── */}
        {sidebarTab === "files" && (
          <>
            <div className="flex shrink-0 items-center justify-between px-4 py-3 border-b border-white/8">
              <span className="text-[10px] font-semibold uppercase tracking-widest text-white/25">Documents</span>
              <button
                onClick={() => fileInputRef.current?.click()}
                disabled={uploading}
                className="flex h-6 w-6 items-center justify-center rounded-md border border-white/10 text-white/40 transition-colors hover:border-white/25 hover:text-white disabled:opacity-40"
              >
                {uploading
                  ? <span className="h-3 w-3 animate-spin rounded-full border border-white/30 border-t-white/80" />
                  : <Plus className="h-3.5 w-3.5" />}
              </button>
              <input ref={fileInputRef} type="file" accept=".txt,.md,.pdf" className="hidden" onChange={handleUpload} />
            </div>

            <div className="flex-1 overflow-y-auto p-3 space-y-1">
              {docs.length === 0 ? (
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="w-full mt-2 flex flex-col items-center gap-3 rounded-xl border-2 border-dashed border-white/10 px-4 py-8 text-center transition-all hover:border-white/20 hover:bg-white/3 group"
                >
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-white/5 group-hover:bg-white/10 transition-colors">
                    <Upload className="h-5 w-5 text-white/30" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-white/40">Drop files here</p>
                    <p className="text-[10px] text-white/20 mt-0.5">PDF · TXT · MD</p>
                  </div>
                </button>
              ) : (
                <>
                  {docs.map((doc) => (
                    <div key={doc.name} className="group flex items-center gap-2.5 px-2.5 py-2 rounded-lg hover:bg-white/5 transition-colors">
                      <FileText className="h-4 w-4 shrink-0 text-white/30" />
                      <div className="flex-1 min-w-0">
                        <p className="truncate text-xs text-white/70 font-medium leading-tight">{doc.name}</p>
                        <p className="text-[10px] text-white/25 mt-0.5">{doc.size_kb} KB</p>
                      </div>
                      <button
                        onClick={() => handleDelete(doc.name)}
                        disabled={deleting === doc.name}
                        className="opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded hover:bg-red-500/20 text-white/20 hover:text-red-400 transition-all"
                      >
                        {deleting === doc.name
                          ? <span className="h-3 w-3 animate-spin rounded-full border border-white/20 border-t-white/60 block" />
                          : <Trash2 className="h-3.5 w-3.5" />}
                      </button>
                    </div>
                  ))}
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full flex items-center gap-2.5 px-2.5 py-2 rounded-lg border border-dashed border-white/8 hover:border-white/15 hover:bg-white/3 transition-all mt-1"
                  >
                    <Upload className="h-3.5 w-3.5 text-white/20" />
                    <span className="text-xs text-white/25">Add more files</span>
                  </button>
                </>
              )}
            </div>

            <div className="shrink-0 border-t border-white/8 px-4 py-3">
              <div className="flex items-center gap-2">
                <CircleDot className={cn("h-3 w-3", docs.length > 0 ? "text-green-500" : "text-white/20")} />
                <span className="text-xs text-white/35">
                  {docs.length} doc{docs.length !== 1 ? "s" : ""} indexed
                </span>
              </div>
            </div>
          </>
        )}

        {/* ─── HISTORY ───────────────────────────────────── */}
        {sidebarTab === "history" && (
          <>
            <div className="shrink-0 px-3 py-3 border-b border-white/8 space-y-2">
              <button
                onClick={handleNewChat}
                className="w-full flex items-center justify-center gap-2 rounded-lg border border-white/10 py-2 text-xs font-medium text-white/45 hover:text-white/75 hover:border-white/20 hover:bg-white/4 transition-colors"
              >
                <PenLine className="h-3.5 w-3.5" />
                New Chat
              </button>
              {/* Search bar */}
              <div className="relative">
                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3 w-3 text-white/25 pointer-events-none" />
                <input
                  type="text"
                  value={historySearch}
                  onChange={(e) => setHistorySearch(e.target.value)}
                  placeholder="Search chats…"
                  className="w-full rounded-lg bg-white/5 border border-white/10 pl-7 pr-7 py-1.5 text-xs text-white/70 placeholder:text-white/25 outline-none focus:border-white/20 transition-colors"
                />
                {historySearch && (
                  <button
                    onClick={() => { setHistorySearch(""); setSearchResults([]); }}
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-white/25 hover:text-white/60"
                  >
                    <X className="h-3 w-3" />
                  </button>
                )}
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-2 space-y-0.5">
              {/* Search results */}
              {historySearch.trim() ? (
                isSearching ? (
                  <div className="flex justify-center mt-6">
                    <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/15 border-t-white/50" />
                  </div>
                ) : searchResults.length === 0 ? (
                  <p className="text-center text-xs text-white/20 mt-8 px-4">No results for &ldquo;{historySearch}&rdquo;</p>
                ) : (
                  <>
                    <p className="text-[10px] font-semibold uppercase tracking-widest text-white/20 px-2 pt-1 pb-0.5">
                      {searchResults.length} result{searchResults.length !== 1 ? "s" : ""}
                    </p>
                    {searchResults.map((r) => (
                      <div
                        key={r.message_id}
                        onClick={() => { handleLoadSession(r.session_id); setHistorySearch(""); setSearchResults([]); }}
                        className="px-2.5 py-2 rounded-lg cursor-pointer hover:bg-white/5 transition-colors group"
                      >
                        <p className="text-[10px] font-semibold text-white/35 truncate mb-0.5 uppercase tracking-wide">{r.session_title}</p>
                        <p className="text-xs text-white/60 leading-relaxed line-clamp-2">
                          {r.content.slice(0, 120)}{r.content.length > 120 ? "…" : ""}
                        </p>
                        <p className="text-[10px] text-white/20 mt-0.5">
                          {new Date(r.created_at).toLocaleDateString(undefined, { month: "short", day: "numeric" })}
                          {" · "}{r.role === "user" ? "You" : "AI"}
                        </p>
                      </div>
                    ))}
                  </>
                )
              ) : (
                /* Normal session list */
                <>
                  {sessions.length === 0 && (
                    <p className="text-center text-xs text-white/20 mt-10 px-4">
                      No previous chats yet
                    </p>
                  )}
                  {sessions.map((s) => (
                    <div
                      key={s.id}
                      onClick={() => handleLoadSession(s.id)}
                      className={cn(
                        "group flex items-center gap-2 px-2.5 py-2 rounded-lg cursor-pointer transition-colors",
                        sessionId === s.id
                          ? "bg-white/8 text-white/70"
                          : "hover:bg-white/5 text-white/40 hover:text-white/65",
                      )}
                    >
                      <MessageSquare className="h-3.5 w-3.5 shrink-0 text-white/20" />
                      <div className="flex-1 min-w-0">
                        <p className="truncate text-xs font-medium leading-tight">{s.title}</p>
                        <p className="text-[10px] text-white/20 mt-0.5">
                          {new Date(s.created_at).toLocaleDateString(undefined, { month: "short", day: "numeric" })}
                        </p>
                      </div>
                      {/* Share button */}
                      <button
                        onClick={(e) => handleShare(e, s.id)}
                        title={sharedSessions.has(s.id) ? "Shared — click to unshare" : "Share chat link"}
                        className={cn(
                          "opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded transition-all",
                          shareCopied === s.id
                            ? "opacity-100 text-emerald-400"
                            : sharedSessions.has(s.id)
                              ? "opacity-100 text-white/40 hover:text-amber-400"
                              : "text-white/15 hover:text-white/50 hover:bg-white/8",
                        )}
                      >
                        {shareCopied === s.id ? <Check className="h-3 w-3" /> : <Share2 className="h-3 w-3" />}
                      </button>
                      {/* Delete button */}
                      <button
                        onClick={(e) => handleDeleteSession(e, s.id)}
                        className="opacity-0 group-hover:opacity-100 flex h-5 w-5 items-center justify-center rounded hover:bg-red-500/15 text-white/15 hover:text-red-400 transition-all"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                </>
              )}
            </div>
          </>
        )}
      </aside>

      {/* ── MAIN AREA ────────────────────────────────────── */}
      <div className="flex flex-1 flex-col min-w-0">

        {/* Top bar */}
        <header className="flex shrink-0 items-center justify-between border-b border-white/8 px-6 py-3">
          <div className="flex items-center gap-3">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="Logo" className="h-6 w-6 rounded object-contain" />
            <span className="text-sm font-semibold text-white tracking-tight">AI Chat</span>
            {messages.length > 0 && (
              <span className="text-xs text-white/20">
                · {messages.filter((m) => m.role === "user").length} question
                {messages.filter((m) => m.role === "user").length !== 1 ? "s" : ""}
              </span>
            )}
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleNewChat}
              className="hidden sm:flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/40 hover:text-white/70 hover:border-white/20 transition-colors"
            >
              <PenLine className="h-3.5 w-3.5" />
              New Chat
            </button>

            <div ref={profileRef} className="relative">
              <button
                onClick={() => setProfileOpen((o) => !o)}
                className="flex items-center gap-2 rounded-full border border-white/10 bg-white/4 pl-1 pr-3 py-1 transition-colors hover:border-white/20 hover:bg-white/8"
              >
                <div className="flex h-7 w-7 items-center justify-center rounded-full bg-white/15 text-xs font-semibold text-white overflow-hidden">
                  {avatarSrc
                    ? <img src={avatarSrc} alt="avatar" className="h-full w-full object-cover" />
                    : avatarLetter}
                </div>
                <span className="hidden text-sm text-white/70 sm:block">{displayName}</span>
                <ChevronDown className={cn("h-3.5 w-3.5 text-white/30 transition-transform", profileOpen && "rotate-180")} />
              </button>

              {profileOpen && (
                <div className="absolute right-0 top-full mt-2 w-52 rounded-xl border border-white/10 bg-[#0f0f0f] shadow-2xl z-50 overflow-hidden">
                  <div className="px-4 py-3 border-b border-white/8">
                    <p className="text-sm font-medium text-white truncate">{displayName}</p>
                    <p className="text-xs text-white/35 truncate mt-0.5">{user?.email}</p>
                  </div>
                  <div className="p-1.5 flex flex-col gap-0.5">
                    <button
                      onClick={() => { setProfileOpen(false); router.push("/profile"); }}
                      className="flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-sm text-white/60 transition-colors hover:bg-white/6 hover:text-white"
                    >
                      <Settings className="h-4 w-4" />
                      Settings
                    </button>
                    <button
                      onClick={() => { setProfileOpen(false); signOut(); }}
                      className="flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-sm text-white/60 transition-colors hover:bg-white/6 hover:text-red-400"
                    >
                      <LogOut className="h-4 w-4" />
                      Sign out
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto">
          {loadingHist ? (
            <div className="flex h-full items-center justify-center">
              <span className="h-5 w-5 animate-spin rounded-full border-2 border-white/20 border-t-white/60" />
            </div>
          ) : (
            <div className="mx-auto max-w-3xl space-y-6 px-4 py-8">
              {messages.length === 0 && (
                <div className="flex flex-col items-center justify-center gap-5 py-20 text-center">
                  <div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
                    <Bot className="h-7 w-7 text-white/30" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-white/50">Ask anything about your documents</p>
                    <p className="mt-1 text-xs text-white/25">
                      {docs.length === 0 ? "Upload a file on the left to get started" : "Your documents are ready — ask a question below"}
                    </p>
                  </div>
                  {docs.length > 0 && (
                    <div className="flex flex-wrap justify-center gap-2">
                      {["Summarize this document", "What are the key points?", "What is the main topic?"].map((s) => (
                        <button
                          key={s}
                          onClick={() => { setInput(s); inputRef.current?.focus(); }}
                          className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/35 hover:text-white/60 hover:border-white/20 transition-colors"
                        >
                          {s}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              )}
              {messages.map((msg) => (
                <MessageBubble
                  key={msg.id}
                  msg={msg}
                  onExport={msg.role === "assistant" && !msg.loading ? handleExport : undefined}
                />
              ))}
              <div ref={bottomRef} />
            </div>
          )}
        </div>

        {/* Input bar */}
        <div className="shrink-0 border-t border-white/8 bg-black px-4 py-4">
          <div className="mx-auto max-w-3xl">
            <div className="flex items-end gap-3 rounded-2xl border border-white/10 bg-[#0f0f0f] px-4 py-3">
              <textarea
                ref={inputRef}
                rows={1}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask a question about your documents…"
                className="flex-1 resize-none bg-transparent text-sm text-white placeholder:text-white/25 focus:outline-none max-h-40"
                style={{ lineHeight: "1.5rem" }}
              />
              {/* Voice input */}
              <button
                onClick={toggleVoice}
                title={listening ? "Stop listening" : "Voice input"}
                className={cn(
                  "mb-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl transition-all",
                  listening
                    ? "bg-red-500/20 text-red-400 animate-pulse"
                    : "text-white/25 hover:text-white/60 hover:bg-white/8",
                )}
              >
                {listening ? <MicOff className="h-3.5 w-3.5" /> : <Mic className="h-3.5 w-3.5" />}
              </button>
              <button
                onClick={sendMessage}
                disabled={!input.trim() || sending}
                className={cn(
                  "mb-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl transition-all",
                  input.trim() && !sending
                    ? "bg-white text-black hover:scale-105 active:scale-95"
                    : "bg-white/10 text-white/20 cursor-not-allowed",
                )}
              >
                <Send className="h-3.5 w-3.5" />
              </button>
            </div>
            <p className="mt-2 text-center text-[11px] text-white/20">
              Multi-turn memory · Grounded answers · Enter to send
              {listening && <span className="ml-2 text-red-400 font-medium">● Listening…</span>}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
